### ISSUE TITLE
Please create some installation manual

### ISSUE THREAD

**Issue by saikek** [ardyesp/DLO-138#14]
First time flashing it's hard to guess what to do, and how to wire programmer.
Can you please reference official PDF `https://jyetech.com/Products/LcdScope/DSO138_oscilloscope_upgrade.pdf` 

and mention that you can use firmware from your `binaries` folder instead of ofiicial firmware using official uploader.

Thank you!

**Comment by dgajew** [comment]
I am affraid you cannot use serial method to upload DLO-138 hex code, I used ST LINK programmer and ST LINK Utility software, without soldering JP1 and JP2 pads. Bootloader probably will be destroyed but this is not problem if you use SWD port instead of TLVL.

**Comment by saikek** [comment]
I was using the method mentioned in the PDF with: 
* soldering JP1 and JP2
* with connecting TX, RX, GND terminals to my 3.3v programmer
* using official tool to read firmware and upload new `.bin` file without any issues

**Comment by ardyesp** [comment]
The readme does mention "Follow the firmware upgrade instructions for DSO-138". I didn't feel it was appropriate to link the document directly.
