### ISSUE TITLE
compiling with arduino IDE 1.8

### ISSUE THREAD

**Issue by cnc4less** [ardyesp/DLO-138#2]
I tried to compile your really great very educational project but I get the following errors

Global variables use 19304 bytes of dynamic memory.
Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
Error compiling for board Generic STM32F103C series.

c:/users/goodness/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/../lib/gcc/arm-none-eabi/4.8.3/../../../../arm-none-eabi/bin/ld.exe: region `rom' overflowed by 13056 bytes

collect2.exe: error: ld returned 1 exit status

please advise
regards

**Comment by ardyesp** [comment]
You should try to setup and compile a Blink example for STM32 board first. See installation and troubleshooting help at [http://www.stm32duino.com](http://www.stm32duino.com)
