### ISSUE TITLE
Creating GUI for displaying data

### ISSUE THREAD

**Issue by nemanjan00** [ardyesp/DLO-138#3]
Hi. 
I have decided to write GUI for displaying data from Serial port. 
To be honest, I am not too good at understanding your code. 
Can you just confirm that there are no special cases except what I see in this dump? 
https://github.com/nemanjan00/dso138-gui/blob/master/example.txt

Thank you!

**Comment by nemanjan00** [comment]
"CH2 Coupling: --, Range: +-2048" is hardcoded?

**Comment by nemanjan00** [comment]
Also, CH2 stats are never shown?

**Comment by ardyesp** [comment]
Yes, there should be no special cases. Since we are not reading Analog CH2 switch position, firmware has no mechanism of knowing the selected timebase and input range. So these stats are not displayed in dump log.
